#Features para nao neutralizar

features = ['feature_intelligence1', 'feature_intelligence4',
       'feature_intelligence7', 'feature_intelligence8',
       'feature_intelligence9', 'feature_intelligence10',
       'feature_intelligence11', 'feature_intelligence12',
       'feature_charisma1', 'feature_charisma4', 'feature_charisma5',
       'feature_charisma8', 'feature_charisma11', 'feature_charisma12',
       'feature_charisma14', 'feature_charisma15', 'feature_charisma18',
       'feature_charisma25', 'feature_charisma30', 'feature_charisma31',
       'feature_charisma32', 'feature_charisma41', 'feature_charisma43',
       'feature_charisma44', 'feature_charisma48', 'feature_charisma50',
       'feature_charisma51', 'feature_charisma53', 'feature_charisma58',
       'feature_charisma63', 'feature_charisma66', 'feature_charisma68',
       'feature_charisma72', 'feature_charisma74', 'feature_charisma77',
       'feature_charisma79', 'feature_charisma80', 'feature_charisma82',
       'feature_charisma84', 'feature_charisma85', 'feature_charisma86',
       'feature_strength3', 'feature_strength4', 'feature_strength7',
       'feature_strength9', 'feature_strength11', 'feature_strength12',
       'feature_strength14', 'feature_strength15', 'feature_strength16',
       'feature_strength17', 'feature_strength21', 'feature_strength22',
       'feature_strength24', 'feature_strength25', 'feature_strength26',
       'feature_strength28', 'feature_strength29', 'feature_strength30',
       'feature_strength31', 'feature_strength34', 'feature_strength36',
       'feature_strength38', 'feature_dexterity1', 'feature_dexterity2',
       'feature_dexterity7', 'feature_dexterity9', 'feature_dexterity10',
       'feature_constitution2', 'feature_constitution3',
       'feature_constitution6', 'feature_constitution13',
       'feature_constitution15', 'feature_constitution16',
       'feature_constitution17', 'feature_constitution18',
       'feature_constitution19', 'feature_constitution21',
       'feature_constitution25', 'feature_constitution26',
       'feature_constitution28', 'feature_constitution33',
       'feature_constitution34', 'feature_constitution36',
       'feature_constitution37', 'feature_constitution38',
       'feature_constitution39', 'feature_constitution41',
       'feature_constitution42', 'feature_constitution50',
       'feature_constitution51', 'feature_constitution52',
       'feature_constitution54', 'feature_constitution58',
       'feature_constitution59', 'feature_constitution60',
       'feature_constitution62', 'feature_constitution66',
       'feature_constitution67', 'feature_constitution69',
       'feature_constitution73', 'feature_constitution74',
       'feature_constitution75', 'feature_constitution78',
       'feature_constitution83', 'feature_constitution90',
       'feature_constitution92', 'feature_constitution95',
       'feature_constitution96', 'feature_constitution97',
       'feature_constitution99', 'feature_constitution100',
       'feature_constitution104', 'feature_constitution106',
       'feature_constitution111', 'feature_constitution113',
       'feature_constitution114', 'feature_wisdom2', 'feature_wisdom3',
       'feature_wisdom4', 'feature_wisdom5', 'feature_wisdom6',
       'feature_wisdom7', 'feature_wisdom9', 'feature_wisdom12',
       'feature_wisdom21', 'feature_wisdom22', 'feature_wisdom23',
       'feature_wisdom24', 'feature_wisdom28', 'feature_wisdom29',
       'feature_wisdom32', 'feature_wisdom34', 'feature_wisdom37',
       'feature_wisdom38', 'feature_wisdom39']